# lesson 1

## numpy

### задание 1

In [1]:
import numpy as np

In [10]:
A = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
A


array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
mean = np.mean(A, axis=0)
mean

array([2. , 8.4])

### Задание 2

In [12]:
mean_a = A - A.mean(axis=0)
mean_a

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

###  Задание 3

In [37]:
a_centered_sp = np.dot(mean_a[:,0],mean_a[:,1])
a_centered_sp

8.0

In [38]:
a_cov = a_centered_sp/(len(mean_a[:,0])-1)
a_cov

2.0

###  Задание 4

In [39]:
np_a_cov = np.cov(A.transpose())
np_a_cov

array([[1. , 2. ],
       [2. , 4.3]])

## Pandas